/// Flutter icons DoctorMaleIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DoctorMaleIcon
///      fonts:
///       - asset: fonts/DoctorMaleIcon.ttf
///
///
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class DoctorMaleIcon {
  DoctorMaleIcon._();

  static const _kFontFam = 'DoctorMaleIcon';

  static const IconData doctor_medical_avatar_health_care_avatar =
      IconData(0xe801, fontFamily: _kFontFam);
}
